
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_FAILED = 'LOG_FAILED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const ROLES_LOADED = 'ROLES_LOADED';
export const ROLES_LOAD_FAILED = 'ROLES_LOOAD_FAILED';
export const CREATE_DOCUMENT_STATUS = 'CREATE_DOCUMENT_STATUS';
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const MESSAGE = 'MESSAGE';
export const GET_USERS = 'GET_USERS';
export const GET_USER  = 'GET_USER';