
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_FAILED = 'LOG_FAILED';
export const SIGNUP_IN_SUCCESS = 'SIGNUP_IN_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const ROLES_LOADED = 'ROLES_LOADED';
export const ROLES_LOAD_FAILED = 'ROLES_LOOAD_FAILED';
